galaxy_info:
  author: Paul Hagedorn <panzer1119@gmail.com>
  description: Set up a QDevice for Proxmox VE cluster quorum enhancement
  license: Apache-2.0
  min_ansible_version: "2.14"
  platforms:
    - name: Debian
      versions:
        - all
  galaxy_tags:
    - system
    - proxmox
    - corosync
    - cluster
