---
- name: "Disable subscription warning (PVE 8.x)"
  replace:
    path: "/usr/share/javascript/proxmox-widget-toolkit/proxmoxlib.js"
    regexp: '\.data\.status\.toLowerCase\(\) !== .active.\) \{'
    replace: ".data.status.toLowerCase() !== 'active' && false) {"
    backup: true
  when: skip_version_check or (pve_version is version('8.2', '>=') and pve_version is version('9.0', '<'))
  notify: "Restart PVE Proxy"
...
